### ISSUE TITLE
tomcat-vault doesn't work with older tomcats

### ISSUE THREAD

**Issue by pierscin** [picketbox/tomcat-vault#52]
There is `Tomcat 8.0.15+` mentioned as required to run this library, but initializing vault with `Tomcat 8.0.28` ends in exception:
```
Initializing Vault
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.tomcat.util.res.StringManager.getManager(Ljava/lang/Class;)Lorg/apache/tomcat/util/res/StringManager;
	at org.apache.tomcat.vault.security.plugins.PBEUtils.<clinit>(PBEUtils.java:49)
	at org.apache.tomcat.vault.VaultSession.computeMaskedPassword(VaultSession.java:161)
	at org.apache.tomcat.vault.VaultSession.startVaultSession(VaultSession.java:191)
	at org.apache.tomcat.vault.VaultInteractiveSession.start(VaultInteractiveSession.java:77)
	at org.apache.tomcat.vault.VaultTool.main(VaultTool.java:120)
```

This is because `getManager(Class<?> clazz)` isn't in older version of `tomcat-util`.

Files with `getManager(Class<?> clazz)`:
```
~/dev/tomcat-vault/src $ ack "getManager\(.*\.class\)" -l | sort
main/java/org/apache/tomcat/vault/security/ExternalPasswordCache.java
main/java/org/apache/tomcat/vault/security/Util.java
main/java/org/apache/tomcat/vault/security/plugins/PBEUtils.java
main/java/org/apache/tomcat/vault/security/vault/PicketBoxSecurityVault.java
main/java/org/apache/tomcat/vault/security/vault/SecurityVaultData.java
main/java/org/apache/tomcat/vault/security/vault/SecurityVaultFactory.java
```
 I changed "newer" invocations of this method on my fork to use method with `String` attribute and it works just fine.

**Comment by csutherl** [comment]
This should be closed since #53 was accepted.
